"Code: VM":
  - changed-files:
      - any-glob-to-any-file: "fern/**"

"Code: JIT":
  - changed-files:
      - any-glob-to-any-file: "jit/**"

"Code: enum_tags":
  - changed-files:
      - any-glob-to-any-file: "enum_tags/**"

"Infra: CI":
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/*"
      
"Infra: Tooling":
  - changed-files:
      - any-glob-to-any-file: ["rustfmt.toml", "Makefile"]
