[workspace]
members = ["fern", "jit"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
license-file = "LICENSE"

[workspace.dependencies]
libc = "0.2.167"
paste = "1.0.15"
static_assertions = "1.1.0"
