[package]
name = "enum_tags"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
